In [1]:
import pandas as pd
from transliterate import translit

In [1]:
with open("Sirena-export-fixed.tab", 'r', encoding='utf-8', newline='') as f:
    buf = f.read()

In [3]:
buf = buf.split("\n")
new_buf = []
for line in buf:
    new_buf.append([line[0:60], 
                    line[60:72], 
                    line[72:84],
                    line[84:96],
                    line[96:108],
                    line[108:120],
                    line[120:132],
                    line[132:138],
                    line[138:144],
                    line[144:150],
                    line[150:168],
                    line[168:180],
                    line[180:186],
                    line[186:192],
                    line[192:198],
                    line[198:204],
                    line[204:216],
                    line[216:240],
                    line[240:276],
                    line[276:336]])
buf = new_buf.copy()

In [4]:
new_buf = []
for line in buf:
    new_buf.append([x.rstrip(" ") for x in line])

In [5]:
data = new_buf[1:]
cols = new_buf[0]

In [6]:
df = pd.DataFrame(data, columns=cols)

In [7]:
new = df["PaxName"].str.split(" ", n = 2, expand = True) 
df["LastName"] = new[0]
df["FirstName"] = new[1]
df["MiddleName"] = new[2]
df['Gender'] = None
df['DepartureCountry'] = None
df['DepartureCity'] = None
df['ArrivalCountry'] = None
df['ArrivalCity'] = None
df['AirlineName'] = None
df['LoyaltyStatus'] = None

In [8]:
df = df.rename(columns={ "PaxName" : "FullName", \
             "PaxBirthDate" : "BirthDate", \
             "FlightCodeSh" : "FlightNumber", \
             "e-Ticket" : "Ticket", \
             "TravelDoc" : "Document", \
             "TrvCls" : "Class", \
             "PaxAdditionalInfo" : "AdditionalInfo", \
             "" : "FF", \
             "AgentInfo" : "AgentInfo",
             "From" : "DepartureAirport", \
             "Dest" : "ArrivalAirport" })

In [9]:
df.head()

,FullName,BirthDate,DepartDate,DepartTime,ArrivalDate,ArrivalTime,FlightNumber,DepartureAirport,ArrivalAirport,Code,...,LastName,FirstName,MiddleName,Gender,DepartureCountry,DepartureCity,ArrivalCountry,ArrivalCity,AirlineName,LoyaltyStatus
0,ОЗЕРОВ ИЛЬДАР ДАНИИЛОВИЧ,1999-05-15,2017-05-30,00:05,2017-05-30,08:05,SU1306NO,SVO,OVB,ZBQSPY,...,ОЗЕРОВ,ИЛЬДАР,ДАНИИЛОВИЧ,None,None,None,None,None,None,None
1,КОЛОСОВ САМИР ТАМЕРЛАНОВИЧ,N/A,2017-12-27,02:15,2017-12-27,04:40,SU1323NO,MMK,SVO,MHPBBX,...,КОЛОСОВ,САМИР,ТАМЕРЛАНОВИЧ,None,None,None,None,None,None,None
2,ИГНАТОВА СНЕЖАНА КОНСТАНТИНОВНА,N/A,2017-09-19,06:40,2017-09-19,07:45,SU1481NO,KJA,SVO,REDLVB,...,ИГНАТОВА,СНЕЖАНА,КОНСТАНТИНОВНА,None,None,None,None,None,None,None
3,ЖАРОВ ПЛАТОН АЛЬБЕРТОВИЧ,1999-05-02,2017-03-18,22:10,2017-03-19,01:05,SU1180NO,SVO,VOG,NSJNGQ,...,ЖАРОВ,ПЛАТОН,АЛЬБЕРТОВИЧ,None,None,None,None,None,None,None
4,НИКОЛЬСКИЙ НИКОЛАЙ ИГОРЕВИЧ,1990-12-26,2017-03-18,22:10,2017-03-19,01:05,SU1180NO,SVO,VOG,VWNYGF,...,НИКОЛЬСКИЙ,НИКОЛАЙ,ИГОРЕВИЧ,None,None,None,None,None,None,None

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155758 entries, 0 to 155757
Data columns (total 30 columns):
FullName            155758 non-null object
BirthDate           155758 non-null object
DepartDate          155758 non-null object
DepartTime          155758 non-null object
ArrivalDate         155758 non-null object
ArrivalTime         155758 non-null object
FlightNumber        155758 non-null object
DepartureAirport    155758 non-null object
ArrivalAirport      155758 non-null object
Code                155758 non-null object
Ticket              155758 non-null object
Document            155758 non-null object
Seat                155758 non-null object
Meal                155758 non-null object
Class               155758 non-null object
Fare                155758 non-null object
Baggage             155758 non-null object
AdditionalInfo      155758 non-null object
FF                  155758 non-null object
AgentInfo           155758 non-null object
LastName            155758 non-null object
FirstName           155757 non-null object
MiddleName          155757 non-null object
Gender              0 non-null object
DepartureCountry    0 non-null object
DepartureCity       0 non-null object
ArrivalCountry      0 non-null object
ArrivalCity         0 non-null object
AirlineName         0 non-null object
LoyaltyStatus       0 non-null object
dtypes: object(30)
memory usage: 35.7+ MB

In [11]:
def condition(x):
    return str(x).lower() == "n/a" or str(x).lower() == "" or x == None


df.BirthDate = df.BirthDate.apply(lambda x: None if condition(x) else str(x).lower())
df.DepartDate = df.DepartDate.apply(lambda x: None if  condition(x) else str(x).lower())
df.DepartTime = df.DepartTime.apply(lambda x: None if  condition(x) else str(x).lower())
df.ArrivalDate = df.ArrivalDate.apply(lambda x: None if  condition(x) else str(x).lower())
df.ArrivalTime = df.ArrivalTime.apply(lambda x: None if  condition(x) else str(x).lower())
df.FlightNumber = df.FlightNumber.apply(lambda x: None if condition(x) else str(x)[:6])
df.DepartureAirport = df.DepartureAirport.apply(lambda x: None if condition(x) else str(x))
df.ArrivalAirport = df.ArrivalAirport.apply(lambda x: None if condition(x) else str(x))
df.Code = df.Code.apply(lambda x: None if condition(x) else str(x))
df.Ticket = df.Ticket.apply(lambda x: None if condition(x) else str(x))
df.Document = df.Document.apply(lambda x: None if  condition(x) else str(x))
df.Seat = df.Seat.apply(lambda x: None if condition(x) else str(x))
df.Meal = df.Meal.apply(lambda x: None if condition(x) else str(x))
df.Class = df.Class.apply(lambda x: None if condition(x) else str(x))
df.Fare = df.Fare.apply(lambda x: None if condition(x) else str(x))
df.Baggage = df.Baggage.apply(lambda x: None if condition(x) else str(x))
df.AdditionalInfo = df.AdditionalInfo.apply(lambda x: None if condition(x) else str(x))
df.FF = df.FF.apply(lambda x: None if condition(x) else str(x)[3:])
df.AgentInfo = df.AgentInfo.apply(lambda x: None if condition(x) else str(x).lower())
df.FullName = df.FullName.apply(lambda x: None if condition(x) else str(translit(str(x), 'ru', reversed=True)).lower())
df.LastName = df.LastName.apply(lambda x: None if condition(x) else str(translit(str(x), 'ru', reversed=True)).lower())
df.FirstName = df.FirstName.apply(lambda x: None if condition(x) else str(translit(str(x), 'ru', reversed=True)).lower())
df.MiddleName = df.MiddleName.apply(lambda x: None if condition(x) else str(translit(str(x), 'ru', reversed=True)).lower())

In [12]:
df.to_csv("tab_processed.csv")